version: "3.7"
services:
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=gusrot
            - POSTGRES_DB=rent-cars
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rent-cars
        ports:
            - 3333:3333
            - 9229:9229
        restart: always
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local

    # network_mode: host
    # environment:
    #   - SEQ_DB=rent-cars
    #   - SEQ_USER=docker
    #   - SEQ_PW=gusrot
    #   - PORT=3333:3333
    #   - DATABASE_URL="postgres://docker:gusrot@db:5432/rent-cars"